#!/usr/bin/env perl
# cv
# Convert files from one MIME type to another
# (c) Reuben Thomas 2006-2023

use strict;
use warnings;

use File::Basename;
use File::MimeInfo;
use Try::Tiny;

use MIME::Convert;
use RRT::Misc;

my $name = basename($0);

# FIXME: Add support for auto-decompression
if ($#ARGV < 1 || $#ARGV > 3) {
  die "Usage: $name IN-FILE OUT-FILE [[OUT-MIME-TYPE] IN-MIME-TYPE]\n";
}

my $infile = shift;
my $outfile = shift;
my $intype = getMimeType($infile);
$intype = mimetype($infile) if $intype eq "binary" || $intype eq "application/octet-stream" || $intype eq "text/plain";
my $outtype;
if ($#ARGV >= 0) {
  $outtype = shift;
} else {
  $outtype = mimetype($outfile);
}
if ($#ARGV == 0) {
  $intype = shift;
}
#print STDERR "$infile $intype $outfile $outtype\n";
if ($outfile eq "-") {
  *OUTFILE = *STDOUT;
} else {
  open OUTFILE, ">$outfile" or die "could not open `$outfile'";
}
try {
  print OUTFILE MIME::Convert::convert($infile, $intype, $outtype, @ARGV);
} catch {
  die "cv: converting $infile ($intype) to $outfile ($outtype): $_";
}
