#!/usr/bin/env python3
# Convert PDF to PostScript
# © Reuben Thomas 2012-2023

import contextlib
import subprocess
import sys
from tempfile import NamedTemporaryFile


file = sys.argv[1]
ctx_mgr = NamedTemporaryFile() if file == "-" else contextlib.nullcontext()
with ctx_mgr as fp:
    if file == "-":
        fp.write(sys.stdin.buffer.read())
        file = fp.name
    subprocess.check_call(["pdf2ps", file, "-"])
