#!/usr/bin/env python3.2
# Hulot converter: text/x-tex→text/html
# © Reuben Thomas 2002-2011

import os
from os.path import basename, dirname
import sys
import tempfile
import re
import subprocess

file = sys.argv[1]
with tempfile.TemporaryDirectory() as tempdir:
    filebase = re.sub('.tex$', '', basename(file)) # FIXME: Better way to parse filenames?
    # FIXME: Move customization of special HeVeA files into web.pl
    subprocess.check_call("cd " + tempdir + "; cp \"" + file + "\" .; env BIBINPUTS=\"" + dirname(file) + ":\" TEXINPUTS=\"" + dirname(file) + ":\" latex-mk --pdflatex \"" + file + "\" > " + tempdir + "/log; hevea -fix -I \"" + os.environ['HOME'] + "/texmf/hevea\" -I \"" + dirname(file) + "\" sym.hva latex2html.hva local.hva \"" + filebase + "\" >> " + tempdir + "/log", shell=True)
    text = open(tempdir + '/' + filebase + '.html', encoding='utf-8').read()
    # Workaround for poems: if no H1, extract title element (if there's a real one, not just the filename) and reinject as H1
    if not re.search('<H1[^>]*>', text, flags=re.IGNORECASE):
        m = re.search('<TITLE[^>]*>(.*)</TITLE>', text, flags=re.MULTILINE | re.DOTALL)
        title = m.group(1)
        if title and title.find('/tmp') == -1:
            text = re.sub('(<BODY[^>]*>)', r'\1<H1>' + title + '</H1>', text)
    sys.stdout.buffer.write(text.encode('utf-8'))
    #print(open(tempdir + "/log").read()), file=sys.stderr) # Useful for debugging
